# -*- coding: utf-8 -*-
"""ec_onda(grafico)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inkxL5pPWa7n_0Tm87Y1Iti_sA2-RMkU
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Cargar los datos generados por C
# fila = tiempo (t), columna = posición (x)
datos = np.loadtxt('datos_onda.csv', delimiter=',')

# VISUALIZACIÓN 1: Fotos en distintos momentos
plt.figure(figsize=(10, 5))

# Elegimos algunos instantes de tiempo para ver cómo avanza el pulso
instantes_a_graficar = [0,50,100,199]

for t in instantes_a_graficar:
    # Asegurarnos de que el tiempo exista en los datos
  if t < len(datos):
    plt.plot(datos[t, :], label=f'Tiempo t={t}')

plt.title('Propagación de la onda (Cortes temporales)')
plt.xlabel('Posición (Nodos)')
plt.ylabel('Amplitud')
plt.legend()
plt.grid(True)
plt.show()

# VISUALIZACIÓN 2: Mapa de calor (Espacio-Tiempo)
# El eje X es el espacio, el eje Y es el tiempo y el color es la amplitud.
# plt.figure(figsize=(10, 6))
# plt.imshow(datos, aspect='auto', cmap='RdBu', origin='lower')
# plt.colorbar(label='Amplitud')
# plt.title('Mapa Espacio-Tiempo de la Onda')
# plt.xlabel('Posición (x)')
# plt.ylabel('Tiempo (t)')
# plt.show()